version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/mail-bounce
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8081:80
    depends_on:
      - backend